using System;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.ComTypes;

namespace Moonlight.WindowsForms
{
    [ComVisible(false), ComImport]
    [Guid("988934A4-064B-11D3-BB80-00104B35E7F9")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IDownloadManager
    {
        [return: MarshalAs(UnmanagedType.I4)]
        [PreserveSig]
        int Download(
            [In, MarshalAs(UnmanagedType.Interface)] IMoniker pmk,
            [In, MarshalAs(UnmanagedType.Interface)] IBindCtx pbc,
            [In, MarshalAs(UnmanagedType.U4)] UInt32 dwBindVerb,
            [In] int grfBINDF,
            [In] IntPtr pBindInfo,
            [In, MarshalAs(UnmanagedType.LPWStr)] string pszHeaders,
            [In, MarshalAs(UnmanagedType.LPWStr)] string pszRedir,
            [In, MarshalAs(UnmanagedType.U4)] uint uiCP);
    }

    [ComImport]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    [Guid("6d5140c1-7436-11ce-8034-00aa006009fa")]
    public interface IServiceProvider
    {
        [PreserveSig]
        int QueryService(ref Guid guidService, ref Guid riid, out IntPtr ppvObject);
    }

    public class NativeMethods
    {

        [DllImport("ole32.dll")]
        public static extern int CreateBindCtx(uint reserved, out IBindCtx ppbc);

        [DllImport("urlmon.dll"), PreserveSig]
        [return: MarshalAs(UnmanagedType.Error)]
        public static extern int CoInternetSetFeatureEnabled(int FeatureEntry, [In, MarshalAs(UnmanagedType.U4)]uint dwFlags, bool fEnable);

    }

    public enum INTERNETFEATURELIST
    {
        /// FEATURE_OBJECT_CACHING -> 0
        FEATURE_OBJECT_CACHING = 0,

        /// FEATURE_ZONE_ELEVATION -> FEATURE_OBJECT_CACHING+1
        FEATURE_ZONE_ELEVATION = (INTERNETFEATURELIST.FEATURE_OBJECT_CACHING + 1),

        /// FEATURE_MIME_HANDLING -> FEATURE_ZONE_ELEVATION+1
        FEATURE_MIME_HANDLING = (INTERNETFEATURELIST.FEATURE_ZONE_ELEVATION + 1),

        /// FEATURE_MIME_SNIFFING -> FEATURE_MIME_HANDLING+1
        FEATURE_MIME_SNIFFING = (INTERNETFEATURELIST.FEATURE_MIME_HANDLING + 1),

        /// FEATURE_WINDOW_RESTRICTIONS -> FEATURE_MIME_SNIFFING+1
        FEATURE_WINDOW_RESTRICTIONS = (INTERNETFEATURELIST.FEATURE_MIME_SNIFFING + 1),

        /// FEATURE_WEBOC_POPUPMANAGEMENT -> FEATURE_WINDOW_RESTRICTIONS+1
        FEATURE_WEBOC_POPUPMANAGEMENT = (INTERNETFEATURELIST.FEATURE_WINDOW_RESTRICTIONS + 1),

        /// FEATURE_BEHAVIORS -> FEATURE_WEBOC_POPUPMANAGEMENT+1
        FEATURE_BEHAVIORS = (INTERNETFEATURELIST.FEATURE_WEBOC_POPUPMANAGEMENT + 1),

        /// FEATURE_DISABLE_MK_PROTOCOL -> FEATURE_BEHAVIORS+1
        FEATURE_DISABLE_MK_PROTOCOL = (INTERNETFEATURELIST.FEATURE_BEHAVIORS + 1),

        /// FEATURE_LOCALMACHINE_LOCKDOWN -> FEATURE_DISABLE_MK_PROTOCOL+1
        FEATURE_LOCALMACHINE_LOCKDOWN = (INTERNETFEATURELIST.FEATURE_DISABLE_MK_PROTOCOL + 1),

        /// FEATURE_SECURITYBAND -> FEATURE_LOCALMACHINE_LOCKDOWN+1
        FEATURE_SECURITYBAND = (INTERNETFEATURELIST.FEATURE_LOCALMACHINE_LOCKDOWN + 1),

        /// FEATURE_RESTRICT_ACTIVEXINSTALL -> FEATURE_SECURITYBAND+1
        FEATURE_RESTRICT_ACTIVEXINSTALL = (INTERNETFEATURELIST.FEATURE_SECURITYBAND + 1),

        /// FEATURE_VALIDATE_NAVIGATE_URL -> FEATURE_RESTRICT_ACTIVEXINSTALL+1
        FEATURE_VALIDATE_NAVIGATE_URL = (INTERNETFEATURELIST.FEATURE_RESTRICT_ACTIVEXINSTALL + 1),

        /// FEATURE_RESTRICT_FILEDOWNLOAD -> FEATURE_VALIDATE_NAVIGATE_URL+1
        FEATURE_RESTRICT_FILEDOWNLOAD = (INTERNETFEATURELIST.FEATURE_VALIDATE_NAVIGATE_URL + 1),

        /// FEATURE_ADDON_MANAGEMENT -> FEATURE_RESTRICT_FILEDOWNLOAD+1
        FEATURE_ADDON_MANAGEMENT = (INTERNETFEATURELIST.FEATURE_RESTRICT_FILEDOWNLOAD + 1),

        /// FEATURE_PROTOCOL_LOCKDOWN -> FEATURE_ADDON_MANAGEMENT+1
        FEATURE_PROTOCOL_LOCKDOWN = (INTERNETFEATURELIST.FEATURE_ADDON_MANAGEMENT + 1),

        /// FEATURE_HTTP_USERNAME_PASSWORD_DISABLE -> FEATURE_PROTOCOL_LOCKDOWN+1
        FEATURE_HTTP_USERNAME_PASSWORD_DISABLE = (INTERNETFEATURELIST.FEATURE_PROTOCOL_LOCKDOWN + 1),

        /// FEATURE_SAFE_BINDTOOBJECT -> FEATURE_HTTP_USERNAME_PASSWORD_DISABLE+1
        FEATURE_SAFE_BINDTOOBJECT = (INTERNETFEATURELIST.FEATURE_HTTP_USERNAME_PASSWORD_DISABLE + 1),

        /// FEATURE_UNC_SAVEDFILECHECK -> FEATURE_SAFE_BINDTOOBJECT+1
        FEATURE_UNC_SAVEDFILECHECK = (INTERNETFEATURELIST.FEATURE_SAFE_BINDTOOBJECT + 1),

        /// FEATURE_GET_URL_DOM_FILEPATH_UNENCODED -> FEATURE_UNC_SAVEDFILECHECK+1
        FEATURE_GET_URL_DOM_FILEPATH_UNENCODED = (INTERNETFEATURELIST.FEATURE_UNC_SAVEDFILECHECK + 1),

        /// FEATURE_ENTRY_COUNT -> FEATURE_GET_URL_DOM_FILEPATH_UNENCODED+1
        FEATURE_ENTRY_COUNT = (INTERNETFEATURELIST.FEATURE_GET_URL_DOM_FILEPATH_UNENCODED + 1),
    }

}
